# This is a basic workflow to help you get started with Actions

name: schedule-2

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: '0 * * * *'
env:
  TOKEN_LINE_NOTIFY: ${{ secrets.TOKEN_LINE_NOTIFY }}
  KEYWORDS: ${{ secrets.KEYWORDS_2 }}
  SORT_TYPE: '0'
  COUNT: '10'
  TOKEN_GOOGLE_SHEET: ${{ secrets.TOKEN_GOOGLE_SHEET }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install python module 
        run: ./init.sh
        
      - name: Run a script
        run: python naver.py
